namespace Jerre.Events
{
    public enum AFEventType
    {
        KILLED, HEALTH_DAMAGE, GAME_OVER, PLAYER_JOIN, PLAYER_LEAVE, SCORE, BOMB_TRIGGER, PLAYER_MENU_BAR_UI_CREATED, RESPAWN, PAUSE_MENU_ENABLE, PAUSE_MENU_DISABLE, ROUND_OVER, COUNT_DOWN_FINISHED, GAME_START
    }
}
